osobki-patch-hotfixi-sbor (5)
* chat-message for syringe

* change dice to prob in machinery

* update-negativeish.dm-jobs

* Update computer.dm

* Update_syringe_fear-because of Diona

* Deleted-Font. trigger=>causes

* desc_for_syringe-update

* bodypart-update

* update-getbodypart

* Add files via upload

* Delete syringes.dm

* experiment

* Update syringes.dm

* Update syringes.dm

* Update syringes.dm

* signal_scared_mood

* New_moodlet

* update-dice_numbers

* bruh_update-projectiles

* rename_triggers

* update_define-traits

* removed_dnd_trait

* removed_dnd_trait-baton

* update_quality-trait_dnd

* deleted_50-syringe

* Update status_effects.dm

* update-debuffs_status_effects

* added_trait-to_dry_hands

* added-check_wet_hands

* re_added-status_dry

* new_status-in_watercloset

error: user.apply_status_effect: undefined proc suka

* need_changes_and_testing

* no_error-no_testing

* removed_dry_trait_maybe_revert

* time_to_remove-dry

* time_to-remove_checks

* ready_to-test

* waterclosed-update

* syringe_fix-update

* remove-descr

* update_feature-wet_gloves

* pull_proc-to_containers

* added_proc-to_containers

* added-FROM

* added-source

* update-source

* added-source

* last-update_probably