Osobo-Negativki (#8885)
* Жирные пальцы (#3)

* Update traits.dm

* description_osobki

* machinery returns

* sink update, but not working__shit

* not working code, no idea how fix it

* now without errors watercloset

* qdel and deltimer or not

* proc in callplace, dont know working or not

* maybe if succes - not needed notice

* deleted not working code

* DnD трейт на рандомный урон (#4)

* dnd-trait

* zapicali

* rolling stunbaton

without errors

* Keep Rolling Projectiles

не тестил

* Reallno rabotaet

* its working clear

* chernovik

* not bad, but without testing

* so funny but not working, fuck

* needed some fix, but without errors

* 0 errors without testing

* working with cool subscryption

* Мокрые руки (#2)

* Update traits.dm

* tosystem

* Kak udalit (nado na vremya)

* copypast from greasy trait

* from machinery to computer emp_acting

* working clear

* Боязнь шприцов (#1)

* traitsdefines

* addtosystem

* 4 errors skeleton

* setting procs

* errors destroyed, but without testing

* its worked, some fixes

* 0 errors, working clear

* added more calls for proc

* old shit

* thats no needed

* ready to merge

* Update code/modules/reagents/reagent_containers/syringes.dm

Co-authored-by: LudwigVonChesterfield <17705613+LudwigVonChesterfield@users.noreply.github.com>

* osobki-patch-hotfixi-sbor (5)

* chat-message for syringe

* change dice to prob in machinery

* update-negativeish.dm-jobs

* Update computer.dm

* Update_syringe_fear-because of Diona

* Deleted-Font. trigger=>causes

* desc_for_syringe-update

* bodypart-update

* update-getbodypart

* Add files via upload

* Delete syringes.dm

* experiment

* Update syringes.dm

* Update syringes.dm

* Update syringes.dm

* signal_scared_mood

* New_moodlet

* update-dice_numbers

* bruh_update-projectiles

* rename_triggers

* update_define-traits

* removed_dnd_trait

* removed_dnd_trait-baton

* update_quality-trait_dnd

* deleted_50-syringe

* Update status_effects.dm

* update-debuffs_status_effects

* added_trait-to_dry_hands

* added-check_wet_hands

* re_added-status_dry

* new_status-in_watercloset

error: user.apply_status_effect: undefined proc suka

* need_changes_and_testing

* no_error-no_testing

* removed_dry_trait_maybe_revert

* time_to_remove-dry

* time_to-remove_checks

* ready_to-test

* waterclosed-update

* syringe_fix-update

* remove-descr

* update_feature-wet_gloves

* pull_proc-to_containers

* added_proc-to_containers

* added-FROM

* added-source

* update-source

* added-source

* last-update_probably

* Patch-osobok-2 (6)

* add_define-update

* Update status_effects.dm

* add_status_effect-define

* update-quality

* last-conflict

* probel_ubran

* Osobki patch 3 (#8)


* Patchim-3 (7)

* clean_hands-define

* water_update-greasy

* clean_hands-effect

* rename

* rename-in_syringes

* Update code/game/machinery/computer/computer.dm

Co-authored-by: LudwigVonChesterfield <17705613+LudwigVonChesterfield@users.noreply.github.com>

* patch 4 (9)

* english-moment

* returning-quality

* rename_var-t

* some-paint_update

* watercloset-update

* without-test

* update-watercloset

* Update status_effects.dm

* Update debuffs.dm

* Update debuffs.dm

* Patch 5 osobki (10)

* Update reagent_containers.dm

* rename_proc

* Update status_effects.dm

* Update code/datums/status_effects/debuffs.dm

Co-authored-by: KIBORG04 <bossmira4@gmail.com>

* not_now, wet_gloves

* Update code/modules/reagents/reagent_containers.dm

Co-authored-by: KIBORG04 <bossmira4@gmail.com>

* short_return

* potential_for_null_ubran

Co-authored-by: LudwigVonChesterfield <17705613+LudwigVonChesterfield@users.noreply.github.com>
Co-authored-by: KIBORG04 <bossmira4@gmail.com>